### ISSUE TITLE
Setup Node and express project

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/DemoApp#1]
This task is to setup initial project. In this task we will create project architecture, necessary files & folders, and install node & express js.

**Comment by ImranBinShoukat** [comment]
I've completed the work on this and pushed the code to GitHub.

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/8

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/6

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/7
