### ISSUE TITLE
Create mock up to upload csv file and modified chat ui on KiboPush

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/DemoApp#10]
This task is to create a mock up to upload csv file and modified chat UI on KiboPush.

For reference, see the design document:
https://docs.google.com/document/d/1yMBFKvNYf9bBIDbNMGg3Bbzo_I6ffMJllcjv07G8dT0/edit#

**Comment by ImranBinShoukat** [comment]
Created the Mock Ups.

**Modified Settings UI to upload customer information file:**

![screenshot from 2018-10-10 12-41-13](https://user-images.githubusercontent.com/17005430/46733792-b3550400-ccaa-11e8-8471-105518f20585.png)

**Modified Chat UI:**

![screenshot from 2018-10-10 15-41-42](https://user-images.githubusercontent.com/17005430/46733800-bcde6c00-ccaa-11e8-8e64-4961b4fffcf1.png)

![screenshot from 2018-10-10 16-03-31](https://user-images.githubusercontent.com/17005430/46733803-bd770280-ccaa-11e8-8de9-645f6eeccd0c.png)

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/12
