### ISSUE TITLE
Client side changes on chat UI on KiboPush

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/DemoApp#11]
This task is to make client side changes on chat UI to show view customer information button and show option to attach customer id.

For reference, see the design document:
https://docs.google.com/document/d/1yMBFKvNYf9bBIDbNMGg3Bbzo_I6ffMJllcjv07G8dT0/edit#

**Comment by ImranBinShoukat** [comment]
Dependent upon #10

**Comment by jekram** [comment]
what is the update here?

**Comment by ImranBinShoukat** [comment]
I have completed the work on this. Assigning @AnishaChhatwani to test

**Comment by AnishaChhatwani** [comment]
Tested

**Comment by jekram** [comment]
thanks
