### ISSUE TITLE
Setup of connection with MongoDB

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/DemoApp#2]
This task to write code to setup database connection for demo app.

**Comment by ImranBinShoukat** [comment]
I've completed the work on this and pushed the code to GitHub.

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/8

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/6

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/7
