### ISSUE TITLE
Create endpoint to attach customer id to the subscriber

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/DemoApp#4]
This task is to create an endpoint to attach customer id to the subscriber. The work for this would be done on KiboPush.

For reference, see the design document:
https://docs.google.com/document/d/1yMBFKvNYf9bBIDbNMGg3Bbzo_I6ffMJllcjv07G8dT0/edit#

**Comment by ImranBinShoukat** [comment]
This is dependent upon #5 and #6

**Comment by AnishaChhatwani** [comment]
Completed the work on this. @ImranBinShoukat please test

**Comment by AnishaChhatwani** [comment]
Completed the work on this. @ImranBinShoukat please test

**Comment by ImranBinShoukat** [comment]
Tested.

**Comment by jekram** [comment]
thanks
