### ISSUE TITLE
Server side work to create customer info records on Demo App

### ISSUE THREAD

**Issue by ImranBinShoukat** [Cloudkibo/DemoApp#6]
This task is to work on serve side to create customer records on demo app.

For reference, see the design document:
https://docs.google.com/document/d/1yMBFKvNYf9bBIDbNMGg3Bbzo_I6ffMJllcjv07G8dT0/edit#

**Comment by ImranBinShoukat** [comment]
This is dependent upon #1 and #2

**Comment by jekram** [comment]
https://github.com/Cloudkibo/DemoApp/issues/7

**Comment by ImranBinShoukat** [comment]
Work on this task has been completed. Assigning @AnishaChhatwani to test this
